version: "3.9"

services:
  backend:
    build: ./python
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./python:/app  # optional for hot reload in dev
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: .
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
